import { Bell } from "lucide-react";
import { fetchNotifications } from "../actions";

export const metadata = { title: "Notifications Center | Admin" };

export default async function NotificationsPage() {
  let notifications: Awaited<ReturnType<typeof fetchNotifications>> = [];
  let error = "";
  try { notifications = await fetchNotifications(); } catch (err: any) { error = err.message || "Unable to load notifications."; }
  return <div className="space-y-6"><div className="border-b pb-5"><h1 className="text-3xl font-bold tracking-tight">Notifications Center</h1><p className="mt-1 text-sm text-muted-foreground">Live resident notifications generated by approved barangay workflows.</p></div>{error && <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">{error}</div>}<div className="overflow-hidden rounded-xl border bg-card shadow-sm"><table className="w-full text-left text-sm"><thead className="border-b bg-muted/50 text-xs font-semibold uppercase text-muted-foreground"><tr><th className="px-6 py-3">Title</th><th className="px-6 py-3">Message</th><th className="px-6 py-3">Created</th><th className="px-6 py-3">Status</th></tr></thead><tbody className="divide-y">{notifications.map((item) => <tr key={item.id}><td className="px-6 py-4 font-medium"><span className="flex items-center gap-2"><Bell className="h-4 w-4 text-primary" />{item.title}</span></td><td className="max-w-xl px-6 py-4 text-muted-foreground">{item.message}</td><td className="px-6 py-4 font-mono text-xs">{new Date(item.created_at).toLocaleString()}</td><td className="px-6 py-4">{item.read_status ? "Read" : "Unread"}</td></tr>)}</tbody></table>{notifications.length === 0 && <p className="p-10 text-center text-sm text-muted-foreground">No notifications recorded.</p>}</div></div>;
}
